### ISSUE TITLE
(Not a bug) Incosistency in spacing for messages

### ISSUE THREAD

**Issue by NICHOLAS85** [zinit-zsh/z-a-submods#1]
A small aesthetic thing, most of the messages printed by Zinit don't include empty newlines whereas this plugin does.

![ksnip_20200226-135943](https://user-images.githubusercontent.com/15698885/75379335-34fb0100-58a3-11ea-9ba1-e844eb490e1c.png)
![ksnip_20200226-140031](https://user-images.githubusercontent.com/15698885/75379333-34626a80-58a3-11ea-803f-fb5555184904.png)

**Comment by psprint** [comment]
I've removed one, the preceding, extra newline. The after-message extra newline apparently comes from Git… But I could not print my regular newline then… Could you check and see if any more spaces need to be removed?

**Comment by NICHOLAS85** [comment]
The following line seems to print an empty line when there is nothing in the `$lines` variable. https://github.com/zinit-zsh/z-a-submods/blob/f9da35c04f4dd7ad6ee144847536b395a32a2326/%E2%86%92za-submods-atpull-handler#L28
Besides that, I don't see any other extra newlines. Do you intend to keep the "Already up to date." message from git visible? You have seemed to hide it for the update action in Zinit.

**Comment by psprint** [comment]
Yes, I'll hide it, thanks.

**Comment by psprint** [comment]
It's done. I'll now have to find some time to implement the `-q/--quiet` option and the `-p/--parallel`-notifying about the new changes.

**Comment by NICHOLAS85** [comment]
Looks good:
![image](https://user-images.githubusercontent.com/15698885/75495717-33a60300-598d-11ea-8430-5bddd1ff3e46.png)
One small thing I noticed, the message hasn't been updated from `z-p-submods` to `z-a-submods`.

A quick question that may be unrelated. Is there an advantage in compiling the `*handler` files in terms of speed? I used to do that but it seems zcompile has an issue compiling the new files due to the `→` character and it made me wonder if that had helped at all anyways.

**Comment by psprint** [comment]
Thanks for noticing the incorrect name.

Yes, compiling the files does have sense. What's the error? I'm AFC.

pt., 28 lut 2020, 00:20 użytkownik NICHOLAS85 <notifications@github.com>
napisał:

**Comment by NICHOLAS85** [comment]
It simply prints a "can't open file" error now:
```
$ zcompile →za-submods-atclone-handler
zcompile: can't open file: →za-submods-atclone-handler
$ cp →za-submods-atclone-handler za-submods-atclone-handler
$ zcompile za-submods-atclone-handler
# No error and *.zwc file is generated
```

**Comment by NICHOLAS85** [comment]
Hey @psprint, just going to some of my old issues and came across this one. Have you looked into the zcompile error I had mentioned in this issue? So you don't have to look for it:

```
$ zcompile →za-submods-atclone-handler
zcompile: can't open file: →za-submods-atclone-handler
$ cp →za-submods-atclone-handler za-submods-atclone-handler
$ zcompile za-submods-atclone-handler
# No error and *.zwc file is generated
```
It seems the `→` character prevents the compilation of these files.

**Comment by psprint** [comment]
I've reported this to zsh-workers ML.
