### ISSUE TITLE
Global git warning when updating submodules

### ISSUE THREAD

**Issue by NICHOLAS85** [zinit-zsh/z-a-submods#3]
Same issue that was solved in Zinit: https://github.com/zdharma/zinit/issues/355

**Comment by psprint** [comment]
The issue should be fixed.

**Comment by NICHOLAS85** [comment]
I believe you accidentally left in a `| \` following your addition causing a parsing error. Removing this solves this and my original issue.

**Comment by psprint** [comment]
It should be fixed now.

**Comment by NICHOLAS85** [comment]
Fixed! Thanks
